version: '3'

services:

  peoplecounter_in_api:
    build:
        context: ./platform_in/
        dockerfile: Dockerfile.prod
    expose:
      - 5000
    env_file:
      - config.env
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=production
      - APP_SETTINGS=app.config.ProductionConfig

  nginx:
    build: ./nginx
    ports:
      - 1339:80
    depends_on:
      - peoplecounter_in_api
