# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TimeRange(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, start_time: datetime=None, end_time: datetime=None):  # noqa: E501
        """TimeRange - a model defined in Swagger

        :param start_time: The start_time of this TimeRange.  # noqa: E501
        :type start_time: datetime
        :param end_time: The end_time of this TimeRange.  # noqa: E501
        :type end_time: datetime
        """
        self.swagger_types = {
            'start_time': datetime,
            'end_time': datetime
        }

        self.attribute_map = {
            'start_time': 'startTime',
            'end_time': 'endTime'
        }

        self._start_time = start_time
        self._end_time = end_time

    @classmethod
    def from_dict(cls, dikt) -> 'TimeRange':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TimeRange of this TimeRange.  # noqa: E501
        :rtype: TimeRange
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start_time(self) -> datetime:
        """Gets the start_time of this TimeRange.


        :return: The start_time of this TimeRange.
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time: datetime):
        """Sets the start_time of this TimeRange.


        :param start_time: The start_time of this TimeRange.
        :type start_time: datetime
        """

        self._start_time = start_time

    @property
    def end_time(self) -> datetime:
        """Gets the end_time of this TimeRange.


        :return: The end_time of this TimeRange.
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time: datetime):
        """Sets the end_time of this TimeRange.


        :param end_time: The end_time of this TimeRange.
        :type end_time: datetime
        """

        self._end_time = end_time
